### PR TITLE
Updating version to 0.2.0.

### PR DESCRIPTION
**Pull request by dhermes**
Also making the necessary docs changes to go along.

/cc @tseaver

### CODE REVIEW

**Comment by dhermes** [comment]
Release notes:

- Removed `google.resumable_media.exceptions` module (moved into `google.resumable_media.common`) (feed0a091ee9118aa4ba36e0748e867d457bce94)
- Making sure we pass unicode to `json.loads()` rather than `bytes`. (#13)

**Comment by jonparrott** [comment]
@dhermes since there is a breaking change (moving a module) shouldn't this be v0.2.0?

**Comment by dhermes** [comment]
OK I'll change `0.1.2` to `0.2.0`.

**Comment by dhermes** [comment]
@jonparrott I updated `0.1.2` to `0.2.0` (though the branch name is still `cut-0.1.2`)

**Comment by dhermes** [comment]
Tag pushed.

Build: https://circleci.com/gh/GoogleCloudPlatform/google-resumable-media-python/159
Release notes: https://github.com/GoogleCloudPlatform/google-resumable-media-python/releases/tag/0.2.0

**Pull request merged**
